import { Country, countryLinks } from './types';
// import countryLinks from '../src/assets/data/countryLinks.json';




//just array, not use as component
//now have countryCode
//now have flagUrl
const goldObject: Country[] = [
    {
        "name": "Afghanistan",
        "countryIndexNumber": 0,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AF",
        "flagUrl": "/public/flagsAF.png"
    },
    {
        "name": "Albania",
        "countryIndexNumber": 1,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "AL",
        "flagUrl": "/public/flagsAL.png"
    },
    {
        "name": "Algeria",
        "countryIndexNumber": 2,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "DZ",
        "flagUrl": "/public/flagsDZ.png"
    },
    {
        "name": "Andorra",
        "countryIndexNumber": 3,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "AD",
        "flagUrl": "/public/flagsAD.png"
    },
    {
        "name": "Angola",
        "countryIndexNumber": 4,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AO",
        "flagUrl": "/public/flagsAO.png"
    },
    {
        "name": "Antigua and Barbuda",
        "countryIndexNumber": 5,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AG",
        "flagUrl": "/public/flagsAG.png"
    },
    {
        "name": "Argentina",
        "countryIndexNumber": 6,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "AR",
        "flagUrl": "/public/flagsAR.png"
    },
    {
        "name": "Armenia",
        "countryIndexNumber": 7,
        "ppm": 750,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "AM",
        "flagUrl": "/public/flagsAM.png"
    },
    {
        "name": "Australia",
        "countryIndexNumber": 8,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AU",
        "flagUrl": "/public/flagsAU.png"
    },
    {
        "name": "Austria",
        "countryIndexNumber": 9,
        "ppm": 1800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AT",
        "flagUrl": "/public/flagsAT.png"
    },
    {
        "name": "Azerbaijan",
        "countryIndexNumber": 10,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "AZ",
        "flagUrl": "/public/flagsAZ.png"
    },
    {
        "name": "Bahamas",
        "countryIndexNumber": 11,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BS",
        "flagUrl": "/public/flagsBS.png"
    },
    {
        "name": "Bahrain",
        "countryIndexNumber": 12,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BH",
        "flagUrl": "/public/flagsBH.png"
    },
    {
        "name": "Bangladesh",
        "countryIndexNumber": 13,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BD",
        "flagUrl": "/public/flagsBD.png"
    },
    {
        "name": "Barbados",
        "countryIndexNumber": 14,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "BB",
        "flagUrl": "/public/flagsBB.png"
    },
    {
        "name": "Belarus",
        "countryIndexNumber": 15,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BY",
        "flagUrl": "/public/flagsBY.png"
    },
    {
        "name": "Belgium",
        "countryIndexNumber": 16,
        "ppm": 1700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BE",
        "flagUrl": "/public/flagsBE.png"
    },
    {
        "name": "Belize",
        "countryIndexNumber": 17,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "BZ",
        "flagUrl": "/public/flagsBZ.png"
    },
    {
        "name": "Benin",
        "countryIndexNumber": 18,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BJ",
        "flagUrl": "/public/flagsBJ.png"
    },
    {
        "name": "Bhutan",
        "countryIndexNumber": 19,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BT",
        "flagUrl": "/public/flagsBT.png"
    },
    {
        "name": "Bolivia",
        "countryIndexNumber": 20,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BO",
        "flagUrl": "/public/flagsBO.png"
    },
    {
        "name": "Bosnia and Herzegovina",
        "countryIndexNumber": 21,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BA",
        "flagUrl": "/public/flagsBA.png"
    },
    {
        "name": "Botswana",
        "countryIndexNumber": 22,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BW",
        "flagUrl": "/public/flagsBW.png"
    },
    {
        "name": "Brazil",
        "countryIndexNumber": 23,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "BR",
        "flagUrl": "/public/flagsBR.png"
    },
    {
        "name": "Brunei",
        "countryIndexNumber": 24,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BN",
        "flagUrl": "/public/flagsBN.png"
    },
    {
        "name": "Bulgaria",
        "countryIndexNumber": 25,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "BG",
        "flagUrl": "/public/flagsBG.png"
    },
    {
        "name": "Burkina Faso",
        "countryIndexNumber": 26,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BF",
        "flagUrl": "/public/flagsBF.png"
    },
    {
        "name": "Burundi",
        "countryIndexNumber": 27,
        "ppm": 300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "BI",
        "flagUrl": "/public/flagsBI.png"
    },
    {
        "name": "Cabo Verde",
        "countryIndexNumber": 28,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CV",
        "flagUrl": "/public/flagsCV.png"
    },
    {
        "name": "Cambodia",
        "countryIndexNumber": 29,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KH",
        "flagUrl": "/public/flagsKH.png"
    },
    {
        "name": "Cameroon",
        "countryIndexNumber": 30,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CM",
        "flagUrl": "/public/flagsCM.png"
    },
    {
        "name": "Canada",
        "countryIndexNumber": 31,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CA",
        "flagUrl": "/public/flagsCA.png"
    },
    {
        "name": "Central African Republic",
        "countryIndexNumber": 32,
        "ppm": 300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CF",
        "flagUrl": "/public/flagsCF.png"
    },
    {
        "name": "Chad",
        "countryIndexNumber": 33,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TD",
        "flagUrl": "/public/flagsTD.png"
    },
    {
        "name": "Chile",
        "countryIndexNumber": 34,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CL",
        "flagUrl": "/public/flagsCL.png"
    },
    {
        "name": "China",
        "countryIndexNumber": 35,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CN",
        "flagUrl": "/public/flagsCN.png"
    },
    {
        "name": "Colombia",
        "countryIndexNumber": 36,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "CO",
        "flagUrl": "/public/flagsCO.png"
    },
    {
        "name": "Comoros",
        "countryIndexNumber": 37,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KM",
        "flagUrl": "/public/flagsKM.png"
    },
    {
        "name": "Congo (Brazzaville)",
        "countryIndexNumber": 38,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CG",
        "flagUrl": "/public/flagsCG.png"
    },
    {
        "name": "Congo (Kinshasa)",
        "countryIndexNumber": 39,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CD",
        "flagUrl": "/public/flagsCD.png"
    },
    {
        "name": "Costa Rica",
        "countryIndexNumber": 40,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "CR",
        "flagUrl": "/public/flagsCR.png"
    },
    {
        "name": "Croatia",
        "countryIndexNumber": 41,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "HR",
        "flagUrl": "/public/flagsHR.png"
    },
    {
        "name": "Cuba",
        "countryIndexNumber": 42,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CU",
        "flagUrl": "/public/flagsCU.png"
    },
    {
        "name": "Cyprus",
        "countryIndexNumber": 43,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "CY",
        "flagUrl": "/public/flagsCY.png"
    },
    {
        "name": "Czech Republic",
        "countryIndexNumber": 44,
        "ppm": 1300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "CZ",
        "flagUrl": "/public/flagsCZ.png"
    },
    {
        "name": "Denmark",
        "countryIndexNumber": 45,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "DK",
        "flagUrl": "/public/flagsDK.png"
    },
    {
        "name": "Djibouti",
        "countryIndexNumber": 46,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "DJ",
        "flagUrl": "/public/flagsDJ.png"
    },
    {
        "name": "Dominica",
        "countryIndexNumber": 47,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "DM",
        "flagUrl": "/public/flagsDM.png"
    },
    {
        "name": "Dominican Republic",
        "countryIndexNumber": 48,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "DO",
        "flagUrl": "/public/flagsDO.png"
    },
    {
        "name": "Ecuador",
        "countryIndexNumber": 49,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "EC",
        "flagUrl": "/public/flagsEC.png"
    },
    {
        "name": "Egypt",
        "countryIndexNumber": 50,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "EG",
        "flagUrl": "/public/flagsEG.png"
    },
    {
        "name": "El Salvador",
        "countryIndexNumber": 51,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "SV",
        "flagUrl": "/public/flagsSV.png"
    },
    {
        "name": "Equatorial Guinea",
        "countryIndexNumber": 52,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GQ",
        "flagUrl": "/public/flagsGQ.png"
    },
    {
        "name": "Eritrea",
        "countryIndexNumber": 53,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ER",
        "flagUrl": "/public/flagsER.png"
    },
    {
        "name": "Estonia",
        "countryIndexNumber": 54,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "EE",
        "flagUrl": "/public/flagsEE.png"
    },
    {
        "name": "Eswatini",
        "countryIndexNumber": 55,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SZ",
        "flagUrl": "/public/flagsSZ.png"
    },
    {
        "name": "Ethiopia",
        "countryIndexNumber": 56,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ET",
        "flagUrl": "/public/flagsET.png"
    },
    {
        "name": "Fiji",
        "countryIndexNumber": 57,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "FJ",
        "flagUrl": "/public/flagsFJ.png"
    },
    {
        "name": "Finland",
        "countryIndexNumber": 58,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "FI",
        "flagUrl": "/public/flagsFI.png"
    },
    {
        "name": "France",
        "countryIndexNumber": 59,
        "ppm": 1700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "FR",
        "flagUrl": "/public/flagsFR.png"
    },
    {
        "name": "Gabon",
        "countryIndexNumber": 60,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GA",
        "flagUrl": "/public/flagsGA.png"
    },
    {
        "name": "Gambia",
        "countryIndexNumber": 61,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GM",
        "flagUrl": "/public/flagsGM.png"
    },
    {
        "name": "Georgia",
        "countryIndexNumber": 62,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "GE",
        "flagUrl": "/public/flagsGE.png"
    },
    {
        "name": "Germany",
        "countryIndexNumber": 63,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "DE",
        "flagUrl": "/public/flagsDE.png"
    },
    {
        "name": "Ghana",
        "countryIndexNumber": 64,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GH",
        "flagUrl": "/public/flagsGH.png"
    },
    {
        "name": "Greece",
        "countryIndexNumber": 65,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "GR",
        "flagUrl": "/public/flagsGR.png"
    },
    {
        "name": "Grenada",
        "countryIndexNumber": 66,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "GD",
        "flagUrl": "/public/flagsGD.png"
    },
    {
        "name": "Guatemala",
        "countryIndexNumber": 67,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GT",
        "flagUrl": "/public/flagsGT.png"
    },
    {
        "name": "Guinea",
        "countryIndexNumber": 68,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GN",
        "flagUrl": "/public/flagsGN.png"
    },
    {
        "name": "Guinea-Bissau",
        "countryIndexNumber": 69,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GW",
        "flagUrl": "/public/flagsGW.png"
    },
    {
        "name": "Guyana",
        "countryIndexNumber": 70,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GY",
        "flagUrl": "/public/flagsGY.png"
    },
    {
        "name": "Haiti",
        "countryIndexNumber": 71,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "HT",
        "flagUrl": "/public/flagsHT.png"
    },
    {
        "name": "Honduras",
        "countryIndexNumber": 72,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "HN",
        "flagUrl": "/public/flagsHN.png"
    },
    {
        "name": "Hungary",
        "countryIndexNumber": 73,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "HU",
        "flagUrl": "/public/flagsHU.png"
    },
    {
        "name": "Iceland",
        "countryIndexNumber": 74,
        "ppm": 2200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "IS",
        "flagUrl": "/public/flagsIS.png"
    },
    {
        "name": "India",
        "countryIndexNumber": 75,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "IN",
        "flagUrl": "/public/flagsIN.png"
    },
    {
        "name": "Indonesia",
        "countryIndexNumber": 76,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ID",
        "flagUrl": "/public/flagsID.png"
    },
    {
        "name": "Iran",
        "countryIndexNumber": 77,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "IR",
        "flagUrl": "/public/flagsIR.png"
    },
    {
        "name": "Iraq",
        "countryIndexNumber": 78,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "IQ",
        "flagUrl": "/public/flagsIQ.png"
    },
    {
        "name": "Ireland",
        "countryIndexNumber": 79,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "IE",
        "flagUrl": "/public/flagsIE.png"
    },
    {
        "name": "Israel",
        "countryIndexNumber": 80,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "IL",
        "flagUrl": "/public/flagsIL.png"
    },
    {
        "name": "Italy",
        "countryIndexNumber": 81,
        "ppm": 1600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "IT",
        "flagUrl": "/public/flagsIT.png"
    },
    {
        "name": "Ivory Coast",
        "countryIndexNumber": 82,
        "ppm": 1400,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CI",
        "flagUrl": "/public/flagsCI.png"
    },
    {
        "name": "Jamaica",
        "countryIndexNumber": 83,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "JM",
        "flagUrl": "/public/flagsJM.png"
    },
    {
        "name": "Japan",
        "countryIndexNumber": 84,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "JP",
        "flagUrl": "/public/flagsJP.png"
    },
    {
        "name": "Jordan",
        "countryIndexNumber": 85,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "JO",
        "flagUrl": "/public/flagsJO.png"
    },
    {
        "name": "Kazakhstan",
        "countryIndexNumber": 86,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KZ",
        "flagUrl": "/public/flagsKZ.png"
    },
    {
        "name": "Kenya",
        "countryIndexNumber": 87,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KE",
        "flagUrl": "/public/flagsKE.png"
    },
    {
        "name": "Kiribati",
        "countryIndexNumber": 88,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KI",
        "flagUrl": "/public/flagsKI.png"
    },
    {
        "name": "Kuwait",
        "countryIndexNumber": 89,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KW",
        "flagUrl": "/public/flagsKW.png"
    },
    {
        "name": "Kyrgyzstan",
        "countryIndexNumber": 90,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KG",
        "flagUrl": "/public/flagsKG.png"
    },
    {
        "name": "Laos",
        "countryIndexNumber": 91,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LA",
        "flagUrl": "/public/flagsLA.png"
    },
    {
        "name": "Latvia",
        "countryIndexNumber": 92,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "LV",
        "flagUrl": "/public/flagsLV.png"
    },
    {
        "name": "Lebanon",
        "countryIndexNumber": 93,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LB",
        "flagUrl": "/public/flagsLB.png"
    },
    {
        "name": "Lesotho",
        "countryIndexNumber": 94,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LS",
        "flagUrl": "/public/flagsLS.png"
    },
    {
        "name": "Liberia",
        "countryIndexNumber": 95,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LR",
        "flagUrl": "/public/flagsLR.png"
    },
    {
        "name": "Libya",
        "countryIndexNumber": 96,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LY",
        "flagUrl": "/public/flagsLY.png"
    },
    {
        "name": "Liechtenstein",
        "countryIndexNumber": 97,
        "ppm": 2500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LI",
        "flagUrl": "/public/flagsLI.png"
    },
    {
        "name": "Lithuania",
        "countryIndexNumber": 98,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LT",
        "flagUrl": "/public/flagsLT.png"
    },
    {
        "name": "Luxembourg",
        "countryIndexNumber": 99,
        "ppm": 2200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "LU",
        "flagUrl": "/public/flagsLU.png"
    },
    {
        "name": "Madagascar",
        "countryIndexNumber": 100,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MG",
        "flagUrl": "/public/flagsMG.png"
    },
    {
        "name": "Malawi",
        "countryIndexNumber": 101,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MW",
        "flagUrl": "/public/flagsMW.png"
    },
    {
        "name": "Malaysia",
        "countryIndexNumber": 102,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "MY",
        "flagUrl": "/public/flagsMY.png"
    },
    {
        "name": "Maldives",
        "countryIndexNumber": 103,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MV",
        "flagUrl": "/public/flagsMV.png"
    },
    {
        "name": "Mali",
        "countryIndexNumber": 104,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ML",
        "flagUrl": "/public/flagsML.png"
    },
    {
        "name": "Malta",
        "countryIndexNumber": 105,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "MT",
        "flagUrl": "/public/flagsMT.png"
    },
    {
        "name": "Marshall Islands",
        "countryIndexNumber": 106,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MH",
        "flagUrl": "/public/flagsMH.png"
    },
    {
        "name": "Mauritania",
        "countryIndexNumber": 107,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MR",
        "flagUrl": "/public/flagsMR.png"
    },
    {
        "name": "Mauritius",
        "countryIndexNumber": 108,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "MU",
        "flagUrl": "/public/flagsMU.png"
    },
    {
        "name": "Mexico",
        "countryIndexNumber": 109,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "MX",
        "flagUrl": "/public/flagsMX.png"
    },
    {
        "name": "Micronesia",
        "countryIndexNumber": 110,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "FM",
        "flagUrl": "/public/flagsFM.png"
    },
    {
        "name": "Moldova",
        "countryIndexNumber": 111,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MD",
        "flagUrl": "/public/flagsMD.png"
    },
    {
        "name": "Monaco",
        "countryIndexNumber": 112,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MC",
        "flagUrl": "/public/flagsMC.png"
    },
    {
        "name": "Mongolia",
        "countryIndexNumber": 113,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MN",
        "flagUrl": "/public/flagsMN.png"
    },
    {
        "name": "Montenegro",
        "countryIndexNumber": 114,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "ME",
        "flagUrl": "/public/flagsME.png"
    },
    {
        "name": "Morocco",
        "countryIndexNumber": 115,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MA",
        "flagUrl": "/public/flagsMA.png"
    },
    {
        "name": "Mozambique",
        "countryIndexNumber": 116,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MZ",
        "flagUrl": "/public/flagsMZ.png"
    },
    {
        "name": "Myanmar",
        "countryIndexNumber": 117,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "MM",
        "flagUrl": "/public/flagsMM.png"
    },
    {
        "name": "Namibia",
        "countryIndexNumber": 118,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "NA",
        "flagUrl": "/public/flagsNA.png"
    },
    {
        "name": "Nauru",
        "countryIndexNumber": 119,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NR",
        "flagUrl": "/public/flagsNR.png"
    },
    {
        "name": "Nepal",
        "countryIndexNumber": 120,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NP",
        "flagUrl": "/public/flagsNP.png"
    },
    {
        "name": "Netherlands",
        "countryIndexNumber": 121,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NL",
        "flagUrl": "/public/flagsNL.png"
    },
    {
        "name": "New Zealand",
        "countryIndexNumber": 122,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NZ",
        "flagUrl": "/public/flagsNZ.png"
    },
    {
        "name": "Nicaragua",
        "countryIndexNumber": 123,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NI",
        "flagUrl": "/public/flagsNI.png"
    },
    {
        "name": "Niger",
        "countryIndexNumber": 124,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NE",
        "flagUrl": "/public/flagsNE.png"
    },
    {
        "name": "Nigeria",
        "countryIndexNumber": 125,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "NG",
        "flagUrl": "/public/flagsNG.png"
    },
    {
        "name": "North Korea",
        "countryIndexNumber": 126,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KP",
        "flagUrl": "/public/flagsKP.png"
    },
    {
        "name": "North Macedonia",
        "countryIndexNumber": 127,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "MK",
        "flagUrl": "/public/flagsMK.png"
    },
    {
        "name": "Norway",
        "countryIndexNumber": 128,
        "ppm": 2200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "NO",
        "flagUrl": "/public/flagsNO.png"
    },
    {
        "name": "Oman",
        "countryIndexNumber": 129,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "OM",
        "flagUrl": "/public/flagsOM.png"
    },
    {
        "name": "Pakistan",
        "countryIndexNumber": 130,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PK",
        "flagUrl": "/public/flagsPK.png"
    },
    {
        "name": "Palau",
        "countryIndexNumber": 131,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PW",
        "flagUrl": "/public/flagsPW.png"
    },
    {
        "name": "Palestine",
        "countryIndexNumber": 132,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PS",
        "flagUrl": "/public/flagsPS.png"
    },
    {
        "name": "Panama",
        "countryIndexNumber": 133,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "PA",
        "flagUrl": "/public/flagsPA.png"
    },
    {
        "name": "Papua New Guinea",
        "countryIndexNumber": 134,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PG",
        "flagUrl": "/public/flagsPG.png"
    },
    {
        "name": "Paraguay",
        "countryIndexNumber": 135,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PY",
        "flagUrl": "/public/flagsPY.png"
    },
    {
        "name": "Peru",
        "countryIndexNumber": 136,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "PE",
        "flagUrl": "/public/flagsPE.png"
    },
    {
        "name": "Philippines",
        "countryIndexNumber": 137,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "PH",
        "flagUrl": "/public/flagsPH.png"
    },
    {
        "name": "Poland",
        "countryIndexNumber": 138,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "PL",
        "flagUrl": "/public/flagsPL.png"
    },
    {
        "name": "Portugal",
        "countryIndexNumber": 139,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "PT",
        "flagUrl": "/public/flagsPT.png"
    },
    {
        "name": "Qatar",
        "countryIndexNumber": 140,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "QA",
        "flagUrl": "/public/flagsQA.png"
    },
    {
        "name": "Romania",
        "countryIndexNumber": 141,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "RO",
        "flagUrl": "/public/flagsRO.png"
    },
    {
        "name": "Russia",
        "countryIndexNumber": 142,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "RU",
        "flagUrl": "/public/flagsRU.png"
    },
    {
        "name": "Rwanda",
        "countryIndexNumber": 143,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "RW",
        "flagUrl": "/public/flagsRW.png"
    },
    {
        "name": "Saint Kitts and Nevis",
        "countryIndexNumber": 144,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "KN",
        "flagUrl": "/public/flagsKN.png"
    },
    {
        "name": "Saint Lucia",
        "countryIndexNumber": 145,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "LC",
        "flagUrl": "/public/flagsLC.png"
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "countryIndexNumber": 146,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "VC",
        "flagUrl": "/public/flagsVC.png"
    },
    {
        "name": "Samoa",
        "countryIndexNumber": 147,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "WS",
        "flagUrl": "/public/flagsWS.png"
    },
    {
        "name": "San Marino",
        "countryIndexNumber": 148,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SM",
        "flagUrl": "/public/flagsSM.png"
    },
    {
        "name": "Sao Tome and Principe",
        "countryIndexNumber": 149,
        "ppm": 866,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ST",
        "flagUrl": "/public/flagsST.png"
    },
    {
        "name": "Saudi Arabia",
        "countryIndexNumber": 150,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SA",
        "flagUrl": "/public/flagsSA.png"
    },
    {
        "name": "Senegal",
        "countryIndexNumber": 151,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SN",
        "flagUrl": "/public/flagsSN.png"
    },
    {
        "name": "Serbia",
        "countryIndexNumber": 152,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "RS",
        "flagUrl": "/public/flagsRS.png"
    },
    {
        "name": "Seychelles",
        "countryIndexNumber": 153,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SC",
        "flagUrl": "/public/flagsSC.png"
    },
    {
        "name": "Sierra Leone",
        "countryIndexNumber": 154,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SL",
        "flagUrl": "/public/flagsSL.png"
    },
    {
        "name": "Singapore",
        "countryIndexNumber": 155,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SG",
        "flagUrl": "/public/flagsSG.png"
    },
    {
        "name": "Slovakia",
        "countryIndexNumber": 156,
        "ppm": 1100,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SK",
        "flagUrl": "/public/flagsSK.png"
    },
    {
        "name": "Slovenia",
        "countryIndexNumber": 157,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "SI",
        "flagUrl": "/public/flagsSI.png"
    },
    {
        "name": "Solomon Islands",
        "countryIndexNumber": 158,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SB",
        "flagUrl": "/public/flagsSB.png"
    },
    {
        "name": "Somalia",
        "countryIndexNumber": 159,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SO",
        "flagUrl": "/public/flagsSO.png"
    },
    {
        "name": "South Africa",
        "countryIndexNumber": 160,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "ZA",
        "flagUrl": "/public/flagsZA.png"
    },
    {
        "name": "South Korea",
        "countryIndexNumber": 161,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "KR",
        "flagUrl": "/public/flagsKR.png"
    },
    {
        "name": "South Sudan",
        "countryIndexNumber": 162,
        "ppm": 489,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SS",
        "flagUrl": "/public/flagsSS.png"
    },
    {
        "name": "Spain",
        "countryIndexNumber": 163,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "ES",
        "flagUrl": "/public/flagsES.png"
    },
    {
        "name": "Sri Lanka",
        "countryIndexNumber": 164,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "LK",
        "flagUrl": "/public/flagsLK.png"
    },
    {
        "name": "Sudan",
        "countryIndexNumber": 165,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SD",
        "flagUrl": "/public/flagsSD.png"
    },
    {
        "name": "Suriname",
        "countryIndexNumber": 166,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SR",
        "flagUrl": "/public/flagsSR.png"
    },
    {
        "name": "Sweden",
        "countryIndexNumber": 167,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SE",
        "flagUrl": "/public/flagsSE.png"
    },
    {
        "name": "Switzerland",
        "countryIndexNumber": 168,
        "ppm": 2200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "CH",
        "flagUrl": "/public/flagsCH.png"
    },
    {
        "name": "Syria",
        "countryIndexNumber": 169,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "SY",
        "flagUrl": "/public/flagsSY.png"
    },
    {
        "name": "Taiwan",
        "countryIndexNumber": 170,
        "ppm": 972,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TW",
        "flagUrl": "/public/flagsTW.png"
    },
    {
        "name": "Tajikistan",
        "countryIndexNumber": 171,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TJ",
        "flagUrl": "/public/flagsTJ.png"
    },
    {
        "name": "Tanzania",
        "countryIndexNumber": 172,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TZ",
        "flagUrl": "/public/flagsTZ.png"
    },
    {
        "name": "Thailand",
        "countryIndexNumber": 173,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true,
        "countryCode": "TH",
        "flagUrl": "/public/flagsTH.png"
    },
    {
        "name": "Timor-Leste",
        "countryIndexNumber": 174,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TL",
        "flagUrl": "/public/flagsTL.png"
    },
    {
        "name": "Togo",
        "countryIndexNumber": 175,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TG",
        "flagUrl": "/public/flagsTG.png"
    },
    {
        "name": "Tonga",
        "countryIndexNumber": 176,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TO",
        "flagUrl": "/public/flagsTO.png"
    },
    {
        "name": "Trinidad and Tobago",
        "countryIndexNumber": 177,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TT",
        "flagUrl": "/public/flagsTT.png"
    },
    {
        "name": "Tunisia",
        "countryIndexNumber": 178,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "TN",
        "flagUrl": "/public/flagsTN.png"
    },
    {
        "name": "Turkey",
        "countryIndexNumber": 179,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false,
        "countryCode": "TR",
        "flagUrl": "/public/flagsTR.png"
    },
    {
        "name": "Turkmenistan",
        "countryIndexNumber": 180,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TM",
        "flagUrl": "/public/flagsTM.png"
    },
    {
        "name": "Tuvalu",
        "countryIndexNumber": 181,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "TV",
        "flagUrl": "/public/flagsTV.png"
    },
    {
        "name": "Uganda",
        "countryIndexNumber": 182,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "UG",
        "flagUrl": "/public/flagsUG.png"
    },
    {
        "name": "Ukraine",
        "countryIndexNumber": 183,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "UA",
        "flagUrl": "/public/flagsUA.png"
    },
    {
        "name": "United Arab Emirates",
        "countryIndexNumber": 184,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "AE",
        "flagUrl": "/public/flagsAE.png"
    },
    {
        "name": "United Kingdom",
        "countryIndexNumber": 185,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "GB",
        "flagUrl": "/public/flagsGB.png"
    },
    {
        "name": "United States",
        "countryIndexNumber": 186,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "US",
        "flagUrl": "/public/flagsUS.png"
    },
    {
        "name": "Uruguay",
        "countryIndexNumber": 187,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "UY",
        "flagUrl": "/public/flagsUY.png"
    },
    {
        "name": "Uzbekistan",
        "countryIndexNumber": 188,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "UZ",
        "flagUrl": "/public/flagsUZ.png"
    },
    {
        "name": "Vanuatu",
        "countryIndexNumber": 189,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "VU",
        "flagUrl": "/public/flagsVU.png"
    },
    {
        "name": "Vatican City",
        "countryIndexNumber": 190,
        "ppm": 2500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "VA",
        "flagUrl": "/public/flagsVA.png"
    },
    {
        "name": "Venezuela",
        "countryIndexNumber": 191,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "VE",
        "flagUrl": "/public/flagsVE.png"
    },
    {
        "name": "Vietnam",
        "countryIndexNumber": 192,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true,
        "countryCode": "VN",
        "flagUrl": "/public/flagsVN.png"
    },
    {
        "name": "Yemen",
        "countryIndexNumber": 193,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "YE",
        "flagUrl": "/public/flagsYE.png"
    },
    {
        "name": "Zambia",
        "countryIndexNumber": 194,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ZM",
        "flagUrl": "/public/flagsZM.png"
    },
    {
        "name": "Zimbabwe",
        "countryIndexNumber": 195,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false,
        "countryCode": "ZW",
        "flagUrl": "/public/flagsZW.png"
    }
].map(country => ({
    ...country, // Keep existing properties
    links: countryLinks[country.name] || {} // Add links dynamically
}));





// const affiliateLinks = {
//     "flights": "https://expedia.com/affiliate/g7BB4rI",
//     "hotels": "https://expedia.com/affiliate/MMigqIa",
//     "attractions": "https://www.viator.com/?pid=P00249582&mcid=42383&medium=link"
// };


// goldObject.forEach(country => {
//     country.affiliateLinks = affiliateLinks;
// });

console.log(goldObject);


export default goldObject;