import { Country } from './types';

const GoldObject: Country[] = [
    {
        "name": "Afghanistan",
        "countryIndexNumber": 0,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Albania",
        "countryIndexNumber": 1,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Algeria",
        "countryIndexNumber": 2,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Andorra",
        "countryIndexNumber": 3,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Angola",
        "countryIndexNumber": 4,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Antigua and Barbuda",
        "countryIndexNumber": 5,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Argentina",
        "countryIndexNumber": 6,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Armenia",
        "countryIndexNumber": 7,
        "ppm": 750,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Australia",
        "countryIndexNumber": 8,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Austria",
        "countryIndexNumber": 9,
        "ppm": 1800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Azerbaijan",
        "countryIndexNumber": 10,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Bahamas",
        "countryIndexNumber": 11,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bahrain",
        "countryIndexNumber": 12,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bangladesh",
        "countryIndexNumber": 13,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Barbados",
        "countryIndexNumber": 14,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Belarus",
        "countryIndexNumber": 15,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Belgium",
        "countryIndexNumber": 16,
        "ppm": 1700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Belize",
        "countryIndexNumber": 17,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Benin",
        "countryIndexNumber": 18,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bhutan",
        "countryIndexNumber": 19,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bolivia",
        "countryIndexNumber": 20,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bosnia and Herzegovina",
        "countryIndexNumber": 21,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Botswana",
        "countryIndexNumber": 22,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Brazil",
        "countryIndexNumber": 23,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Brunei",
        "countryIndexNumber": 24,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Bulgaria",
        "countryIndexNumber": 25,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Burkina Faso",
        "countryIndexNumber": 26,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Burundi",
        "countryIndexNumber": 27,
        "ppm": 300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Cabo Verde",
        "countryIndexNumber": 28,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Cambodia",
        "countryIndexNumber": 29,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Cameroon",
        "countryIndexNumber": 30,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Canada",
        "countryIndexNumber": 31,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Central African Republic",
        "countryIndexNumber": 32,
        "ppm": 300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Chad",
        "countryIndexNumber": 33,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Chile",
        "countryIndexNumber": 34,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "China",
        "countryIndexNumber": 35,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Colombia",
        "countryIndexNumber": 36,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Comoros",
        "countryIndexNumber": 37,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Congo (Brazzaville)",
        "countryIndexNumber": 38,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Congo (Kinshasa)",
        "countryIndexNumber": 39,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Costa Rica",
        "countryIndexNumber": 40,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Croatia",
        "countryIndexNumber": 41,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Cuba",
        "countryIndexNumber": 42,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Cyprus",
        "countryIndexNumber": 43,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Czech Republic",
        "countryIndexNumber": 44,
        "ppm": 1300,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Denmark",
        "countryIndexNumber": 45,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Djibouti",
        "countryIndexNumber": 46,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Dominica",
        "countryIndexNumber": 47,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Dominican Republic",
        "countryIndexNumber": 48,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Ecuador",
        "countryIndexNumber": 49,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Egypt",
        "countryIndexNumber": 50,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "El Salvador",
        "countryIndexNumber": 51,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Equatorial Guinea",
        "countryIndexNumber": 52,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Eritrea",
        "countryIndexNumber": 53,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Estonia",
        "countryIndexNumber": 54,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Eswatini",
        "countryIndexNumber": 55,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Ethiopia",
        "countryIndexNumber": 56,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Fiji",
        "countryIndexNumber": 57,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Finland",
        "countryIndexNumber": 58,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "France",
        "countryIndexNumber": 59,
        "ppm": 1700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Gabon",
        "countryIndexNumber": 60,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Gambia",
        "countryIndexNumber": 61,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Georgia",
        "countryIndexNumber": 62,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Germany",
        "countryIndexNumber": 63,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Ghana",
        "countryIndexNumber": 64,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Greece",
        "countryIndexNumber": 65,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Grenada",
        "countryIndexNumber": 66,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Guatemala",
        "countryIndexNumber": 67,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Guinea",
        "countryIndexNumber": 68,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Guinea-Bissau",
        "countryIndexNumber": 69,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Guyana",
        "countryIndexNumber": 70,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Haiti",
        "countryIndexNumber": 71,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Honduras",
        "countryIndexNumber": 72,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Hungary",
        "countryIndexNumber": 73,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Iceland",
        "countryIndexNumber": 74,
        "ppm": 2200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "India",
        "countryIndexNumber": 75,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Indonesia",
        "countryIndexNumber": 76,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Iran",
        "countryIndexNumber": 77,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Iraq",
        "countryIndexNumber": 78,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Ireland",
        "countryIndexNumber": 79,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Israel",
        "countryIndexNumber": 80,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Italy",
        "countryIndexNumber": 81,
        "ppm": 1600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Ivory Coast",
        "countryIndexNumber": 82,
        "ppm": 0,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Jamaica",
        "countryIndexNumber": 83,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Japan",
        "countryIndexNumber": 84,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Jordan",
        "countryIndexNumber": 85,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Kazakhstan",
        "countryIndexNumber": 86,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Kenya",
        "countryIndexNumber": 87,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Kiribati",
        "countryIndexNumber": 88,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Kuwait",
        "countryIndexNumber": 89,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Kyrgyzstan",
        "countryIndexNumber": 90,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Laos",
        "countryIndexNumber": 91,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Latvia",
        "countryIndexNumber": 92,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Lebanon",
        "countryIndexNumber": 93,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Lesotho",
        "countryIndexNumber": 94,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Liberia",
        "countryIndexNumber": 95,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Libya",
        "countryIndexNumber": 96,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Liechtenstein",
        "countryIndexNumber": 97,
        "ppm": 2500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Lithuania",
        "countryIndexNumber": 98,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Luxembourg",
        "countryIndexNumber": 99,
        "ppm": 2200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Madagascar",
        "countryIndexNumber": 100,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Malawi",
        "countryIndexNumber": 101,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Malaysia",
        "countryIndexNumber": 102,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Maldives",
        "countryIndexNumber": 103,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Mali",
        "countryIndexNumber": 104,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Malta",
        "countryIndexNumber": 105,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Marshall Islands",
        "countryIndexNumber": 106,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Mauritania",
        "countryIndexNumber": 107,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Mauritius",
        "countryIndexNumber": 108,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Mexico",
        "countryIndexNumber": 109,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Micronesia",
        "countryIndexNumber": 110,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Moldova",
        "countryIndexNumber": 111,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Monaco",
        "countryIndexNumber": 112,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Mongolia",
        "countryIndexNumber": 113,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Montenegro",
        "countryIndexNumber": 114,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Morocco",
        "countryIndexNumber": 115,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Mozambique",
        "countryIndexNumber": 116,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Myanmar",
        "countryIndexNumber": 117,
        "ppm": 0,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Namibia",
        "countryIndexNumber": 118,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Nauru",
        "countryIndexNumber": 119,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Nepal",
        "countryIndexNumber": 120,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Netherlands",
        "countryIndexNumber": 121,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "New Zealand",
        "countryIndexNumber": 122,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Nicaragua",
        "countryIndexNumber": 123,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Niger",
        "countryIndexNumber": 124,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Nigeria",
        "countryIndexNumber": 125,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "North Korea",
        "countryIndexNumber": 126,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "North Macedonia",
        "countryIndexNumber": 127,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Norway",
        "countryIndexNumber": 128,
        "ppm": 2200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Oman",
        "countryIndexNumber": 129,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Pakistan",
        "countryIndexNumber": 130,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Palau",
        "countryIndexNumber": 131,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Palestine",
        "countryIndexNumber": 132,
        "ppm": 0,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Panama",
        "countryIndexNumber": 133,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Papua New Guinea",
        "countryIndexNumber": 134,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Paraguay",
        "countryIndexNumber": 135,
        "ppm": 700,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Peru",
        "countryIndexNumber": 136,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Philippines",
        "countryIndexNumber": 137,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Poland",
        "countryIndexNumber": 138,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Portugal",
        "countryIndexNumber": 139,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Qatar",
        "countryIndexNumber": 140,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Romania",
        "countryIndexNumber": 141,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Russia",
        "countryIndexNumber": 142,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Rwanda",
        "countryIndexNumber": 143,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Saint Kitts and Nevis",
        "countryIndexNumber": 144,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Saint Lucia",
        "countryIndexNumber": 145,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "countryIndexNumber": 146,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Samoa",
        "countryIndexNumber": 147,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "San Marino",
        "countryIndexNumber": 148,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Sao Tome and Principe",
        "countryIndexNumber": 149,
        "ppm": 0,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Saudi Arabia",
        "countryIndexNumber": 150,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Senegal",
        "countryIndexNumber": 151,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Serbia",
        "countryIndexNumber": 152,
        "ppm": 900,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Seychelles",
        "countryIndexNumber": 153,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Sierra Leone",
        "countryIndexNumber": 154,
        "ppm": 400,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Singapore",
        "countryIndexNumber": 155,
        "ppm": 2000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Slovakia",
        "countryIndexNumber": 156,
        "ppm": 1100,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Slovenia",
        "countryIndexNumber": 157,
        "ppm": 1300,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Solomon Islands",
        "countryIndexNumber": 158,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Somalia",
        "countryIndexNumber": 159,
        "ppm": 400,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "South Africa",
        "countryIndexNumber": 160,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "South Korea",
        "countryIndexNumber": 161,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "South Sudan",
        "countryIndexNumber": 162,
        "ppm": 0,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Spain",
        "countryIndexNumber": 163,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Sri Lanka",
        "countryIndexNumber": 164,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Sudan",
        "countryIndexNumber": 165,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Suriname",
        "countryIndexNumber": 166,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Sweden",
        "countryIndexNumber": 167,
        "ppm": 1900,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Switzerland",
        "countryIndexNumber": 168,
        "ppm": 2200,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Syria",
        "countryIndexNumber": 169,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Taiwan",
        "countryIndexNumber": 170,
        "ppm": 0,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": true,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Tajikistan",
        "countryIndexNumber": 171,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Tanzania",
        "countryIndexNumber": 172,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Thailand",
        "countryIndexNumber": 173,
        "ppm": 1000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": true
    },
    {
        "name": "Timor-Leste",
        "countryIndexNumber": 174,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Togo",
        "countryIndexNumber": 175,
        "ppm": 500,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Tonga",
        "countryIndexNumber": 176,
        "ppm": 1200,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Trinidad and Tobago",
        "countryIndexNumber": 177,
        "ppm": 1500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Tunisia",
        "countryIndexNumber": 178,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Turkey",
        "countryIndexNumber": 179,
        "ppm": 1000,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": true,
        "nomadVisa": false
    },
    {
        "name": "Turkmenistan",
        "countryIndexNumber": 180,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Tuvalu",
        "countryIndexNumber": 181,
        "ppm": 1500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Uganda",
        "countryIndexNumber": 182,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Ukraine",
        "countryIndexNumber": 183,
        "ppm": 700,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "United Arab Emirates",
        "countryIndexNumber": 184,
        "ppm": 2000,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "United Kingdom",
        "countryIndexNumber": 185,
        "ppm": 1800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "United States",
        "countryIndexNumber": 186,
        "ppm": 2500,
        "coast": true,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Uruguay",
        "countryIndexNumber": 187,
        "ppm": 1200,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Uzbekistan",
        "countryIndexNumber": 188,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Vanuatu",
        "countryIndexNumber": 189,
        "ppm": 800,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Vatican City",
        "countryIndexNumber": 190,
        "ppm": 2500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Venezuela",
        "countryIndexNumber": 191,
        "ppm": 800,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Vietnam",
        "countryIndexNumber": 192,
        "ppm": 600,
        "coast": true,
        "englishSpeaking": false,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": true
    },
    {
        "name": "Yemen",
        "countryIndexNumber": 193,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": false,
        "affordableDining": false,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Zambia",
        "countryIndexNumber": 194,
        "ppm": 600,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": false,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    },
    {
        "name": "Zimbabwe",
        "countryIndexNumber": 195,
        "ppm": 500,
        "coast": false,
        "englishSpeaking": true,
        "affordableDining": true,
        "unsafe": true,
        "affordableEducation": false,
        "affordableHealthCare": false,
        "nomadVisa": false
    }
]

export default GoldObject;